server:
  port: 6031
spring:
  application:
    name: dome
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6011/eureka/
      #http://127.0.0.1:6012/eureka/,http://127.0.0.1:6013/eureka/#